export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_HISTORY = 'ADD_HISTORY';
export const SET_CURRENT_USERID = 'SET_CURRENT_USERID';
export const SET_CURRENT_USER_FIRSTNAME = 'SET_CURRENT_USER_FIRSTNAME';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

