export const ADD_MESSAGE = 'App/ADD_MESSAGE';
export const ADD_HISTORY = 'App/ADD_HISTORY';
export const SET_CURRENT_USERID = 'App/SET_CURRENT_USERID';
export const SET_CURRENT_USER_FIRSTNAME = 'App/SET_CURRENT_USER_FIRSTNAME';
export const SET_AUTH_TOKEN = 'App/SET_AUTH_TOKEN';

